services:
  wiremock:
    image: rodolpheche/wiremock
    container_name: wiremock-server
    volumes:
      - ./__files:/home/wiremock/__files
      - ./mappings:/home/wiremock/mappings
    ports:
      - 8080:8080
